### ISSUE TITLE
Desenvolver Planejamento

### ISSUE THREAD

**Issue by EduardoGurgel** [fga-eps-mds/2023-2-GEROcuidado-Doc#10]
# Descrição
Desenvolver Quadro de conhecimento, Quadro de disponibilidade, Quadro de pareamento, Cronograma de dojo, Plano de qualidade, Plano de custos, Plano de gerenciamento de risco e documento de metodologias.

# Tarefas
Aba responsável por inserir as demandas desta issue.

- [x] #16
- [x] #1
- [x] #39
- [x] #63
- [x] #15
- [x] #13 
- [x] #14
- [x] #62
- [x] #64
- [x] #65
- [ ] #72
- [x] #73
- [ ]  #67 
- [x] #120 

# Critérios de Aceitação
O que foi concluído até o momento.
- [ ] Quadro de conhecimento adicionado ao gitpages
- [x] Quadro de disponibilidade adicionado ao gitpages
- [ ] Quadro de pareamento adicionado ao gitpages 
- [x] Cronograma de dojo adicionado ao gitpages
- [ ] Plano de qualidade adicionado ao gitpages
- [ ] Plano de custos adicionado ao gitpages
- [ ] Plano de gerenciamento de risco adicionado ao gitpages
- [ ] Documento de metodologia adicionado ao gitpages
