### ISSUE TITLE
Atualização dos documentos

### ISSUE THREAD

**Issue by pedro-cella** [fga-eps-mds/2023-2-GEROcuidado-Doc#215]
# Descrição
Atualizar documentação e fazer o Analytics.

# Tarefas
Aba responsável por inserir as demandas desta issue.

- [x] Atualizar EAP;
- [x] Atualizar Documento de Banco de Dados;
- [ ] Atualizar Protótipo;
- [x] Atualizar Quadro de conhecimento;
- [x] Atualizar Documento de metodologias;
- [x] Atualizar Plano de custo;
- [x] Atualizar EVM;
- [x] Implementar o notebook de Analytics;
- [x] Criar e adicionar arquivo de Post Mortem;
- [x] Atualizar parte de Monitoramento;

# Critérios de Aceitação
O que foi concluído até o momento.
- [x] EAP atualizado;
- [x] Documento de Banco de Dados atualizado;
- [x] Documento do protótipo atualizado;
- [x] Quadro de conhecimento atualizado;
- [x] Documento de metodologias atualizado;
- [x] Plano de custo atualizado;
- [x] EVM atualizado;
- [x] Analytics criado;
- [x] Post Mortem criado;
- [x] Parte de Monitoramento atualizada;
