### ISSUE TITLE
Lean Inception

### ISSUE THREAD

**Issue by pedro-cella** [fga-eps-mds/2023-2-GEROcuidado-Doc#30]
# Descrição
Épico destinado a execução das atividades de desenvolvimento do Lean Inception

# Tarefas
- [x] Lean Inception Kick Off
- [ ] Lean Inception Dia 1 (Visão do produto, É/não é - Faz/não faz e Objetivos do produto );
- [ ] Lean Inception Dia 2 (Descrição das personas e Jornadas do usuário);
- [ ] Lean Inception Dia 3 (Brainstorm de funcionalidades e revisão técnica de negócio e UX);
- [ ] Lean Inception Dia 4 (Sequenciador e Canvas MVP);
- [ ] Lean Inception Showcase

# Critérios de Aceitação
- [ ] Todas as atividades do Lean Inception foram feitas
