### ISSUE TITLE
Lean Inception

### ISSUE THREAD

**Issue by pedro-cella** [fga-eps-mds/2023-2-GEROcuidado-Doc#31]
# Descrição
Épico destinado a execução das atividades de desenvolvimento do Lean Inception

# Tarefas
- [x] Lean Inception Kick Off
- [x] Lean Inception Dia 1 (Visão do produto, É/não é - Faz/não faz e Objetivos do produto );
- [x] Lean Inception Dia 2 (Descrição das personas e Jornadas do usuário);
- [x] Lean Inception Dia 3 (Brainstorm de funcionalidades e revisão técnica de negócio e UX);
- [x] Lean Inception Dia 4 (Sequenciador e Canvas MVP);
- [x] Lean Inception Showcase

# Critérios de Aceitação

- [ ] Todas as atividades do Lean Inception foram feitas

**Comment by pedro-cella** [comment]
Cronograma inicial do Lean Inception do projeto

![Captura de tela de 2023-09-25 16-24-43](https://github.com/fga-eps-mds/2023-2-GEROcuidado-Doc/assets/49076513/37c0d951-88ec-4bae-ab41-7f7e4d73c859)
