### ISSUE TITLE
RoadMap do Projeto

### ISSUE THREAD

**Issue by EduardoGurgel** [fga-eps-mds/2023-2-GEROcuidado-Doc#64]
# Descrição
Criar roadmap do projeto

# Tarefas
- [x] Manter roadmap atualizado no Zenhub;
- [x] Documentar roadmap;

# Critérios de Aceitação
- [x] Roadmap devidamente atualizado no Zenhub;
- [x] Roadmap adicionado ao gitpages

**Comment by pedro-cella** [comment]
Criação do Roadmap realizada e já feita no Zenhub

![image](https://github.com/fga-eps-mds/2023-2-GEROcuidado-Doc/assets/49076513/6d17ea18-eb5e-456d-b136-b8e760beb1d0)
